// DO NOT EDIT THIS FILE
namespace Editor {
	public class StickerPacksBuilderMeta : BaseBuilderMeta<StickerPacksBuilderMeta> {
		public override string AssetName => "__stickers_builder_meta.asset";
		public override string BaseFolder => "Content/StickerPacks";

		public override string Ext => ".knsp";
		public override string DefaultBuildFolder => "Build/StickerPacks";
	}
}