// DO NOT EDIT THIS FILE

namespace Editor {
	public class CustomObjectsBuilderMeta : BaseBuilderMeta<CustomObjectsBuilderMeta> {
		public override string AssetName => "__objects_builder_meta.asset";
		public override string BaseFolder => "Content/CustomObjects";

		public override string Ext => ".knco";
		public override string DefaultBuildFolder => "Build/CustomObjects";
	}
}