using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

// DO NOT EDIT THIS FILE
namespace Editor {
	public abstract class BaseMeta<T> : ScriptableObject where T : Object {
		public abstract bool Validate();

		public static T GetInstance() {
			string typeName = typeof(T).Name;

			var guids = AssetDatabase.FindAssets($"t:{typeName}");
			if (guids == null || guids.Length == 0) {
				Debug.LogError($"Kino: Unable to locate {typeName} asset");
				return default;
			}

			if (guids.Length > 1) {
				Debug.LogError($"Kino: Multiple {typeName} assets defined. Only one {typeName} should be defined in the project");
				return default;
			}

			string path = AssetDatabase.GUIDToAssetPath(guids[0]);
			return (T) AssetDatabase.LoadAssetAtPath(path, typeof(T));
		}

		public static IEnumerable<T> GetAllInstances() {
			string typeName = typeof(T).Name;

			var guids = AssetDatabase.FindAssets($"t:{typeName}");

			var packsList = new List<T>();

			foreach (var guid in guids) {
				string path = AssetDatabase.GUIDToAssetPath(guid);
				var meta = AssetDatabase.LoadAssetAtPath<T>(path);

				if (meta) {
					packsList.Add(meta);
				}
			}

			return packsList;
		}
	}

	public abstract class BaseEntryMeta<T> : BaseMeta<T> where T : Object {
		public bool SelectedToBuild = true;

		[Tooltip("Pack name.\nIt should be in lowercase, consist only of Latin letters, numbers, and underscores (_), with <color=red>NO</color> spaces.")]
		public string Name = "item_name";

		public virtual void RefreshEditor() { }

		public string GetRoot() {
			string assetPath = AssetDatabase.GetAssetPath(this);
			var rootFolder = Path.GetDirectoryName(assetPath);
			if (string.IsNullOrWhiteSpace(rootFolder)) {
				Debug.LogError($"Kino: Unable to get {typeof(T).Name} asset directory");
				return null;
			}

			return rootFolder;
		}
	}

	public abstract class BaseEditorMeta<T> : BaseMeta<T> where T : Object {
		public abstract string AssetName { get; }
		public abstract string BaseFolder { get; }
	}

	public abstract class BaseBuilderMeta<T> : BaseEditorMeta<T> where T : Object {
		public virtual int Version => 600;
		public abstract string Ext { get; }
		public abstract string DefaultBuildFolder { get; }

		[Tooltip("Specify the folder in which you want to put the build result")]
		public string BuildFolder = string.Empty;

		public override bool Validate() {
			if (string.IsNullOrWhiteSpace(BuildFolder)) {
				BuildFolder = DefaultBuildFolder;
			}

			if (!Directory.Exists(BuildFolder)) {
				Directory.CreateDirectory(BuildFolder);
			}

			return true;
		}
	}
}