using UnityEditor;

// DO NOT EDIT THIS FILE
namespace Editor {
	public class EditorPanel : EditorWindow {
		[MenuItem("Kino/Car Parts build tool", false, 0)]
		public static void OpenPartsWindow() {
			GetWindow(typeof(CarPartsTool));
		}

		[MenuItem("Kino/Sticker packs tool", false, 1)]
		public static void OpenStickersWindow() {
			GetWindow(typeof(StickerPacksTool));
		}

		[MenuItem("Kino/Custom Objects tool", false, 2)]
		public static void OpenObjectsWindow() {
			GetWindow(typeof(CustomObjectsTool));
		}

		[MenuItem("Kino/Maps tool", false, 3)]
		public static void OpenMapsWindow() {
			GetWindow(typeof(MapsTool));
		}
	}
}