using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using UnityEditor;
using UnityEngine;
using Debug = UnityEngine.Debug;

// DO NOT EDIT THIS FILE
namespace Editor {
  public class PacksTool : EditorWindow {
    private const float OFFSET = 5.0f;

    private AuthorMeta authorMeta_;
    private readonly List<PartPackMeta> packs_ = new List<PartPackMeta>();

    private readonly PacksBuilder builder_ = new PacksBuilder();

    private Vector2 scrollPos_ = Vector2.zero;

    [MenuItem("Kino/Packs build tool")]
    public static void ShowWindow() {
      GetWindow(typeof(PacksTool));
    }

    [MenuItem("Kino/Open Build folder")]
    private static void OpenBuildFolder() {
      string buildPath = Path.Combine(Application.dataPath, PacksBuilder.BUILD_DIR);
      if (Directory.Exists(buildPath)) {
        Process.Start(buildPath);
      }
      else {
        Debug.LogError("Kino: Unable to open build packs folder, the folder doesn't exists");
      }
    }

    private void OnFocus() {
      Refresh();
    }

    private void OnGUI() {
      if (!EnsureMetaLoaded()) {
        GUILayout.Label("Unable to load meta, see console for errors", EditorStyles.boldLabel);
        return;
      }

      DrawAuthorMeta();

      DrawPacks();

      DrawButtons();
    }

    private void DrawAuthorMeta() {
      bool guiEnabled = GUI.enabled;

      GUI.enabled = false;

      GUILayout.Label("Author name:", EditorStyles.boldLabel);
      EditorGUILayout.TextField(authorMeta_.Name);

      GUILayout.Label("Author SteamID:", EditorStyles.boldLabel);
      EditorGUILayout.LongField((long)authorMeta_.SteamId);

      GUILayout.Label("Author DiscordID:", EditorStyles.boldLabel);
      EditorGUILayout.LongField((long)authorMeta_.DiscordId);

      GUILayout.Space(OFFSET);

      GUI.enabled = true;
      if (GUILayout.Button("Edit")) {
        Utils.SelectObject(authorMeta_);
      }

      GUI.enabled = guiEnabled;

      DrawHorizontalGUILine();
    }

    private void DrawPacks() {
      GUILayout.Label("Part packs:", EditorStyles.boldLabel);

      EditorGUILayout.Space(OFFSET);

      scrollPos_ = GUILayout.BeginScrollView(scrollPos_);
      foreach (var pack in packs_) {
        GUILayout.Label(pack.PackName, EditorStyles.boldLabel);

        GUILayout.BeginHorizontal();

        pack.SelectedToBuild = EditorGUILayout.Toggle("Selected to build", pack.SelectedToBuild);
        if (GUILayout.Button("Edit")) {
          Utils.SelectObject(pack);
        }

        GUILayout.EndHorizontal();

        EditorGUILayout.Space(OFFSET);
        DrawHorizontalGUILine();
      }

      GUILayout.EndScrollView();
    }

    private void DrawButtons() {
      DrawHorizontalGUILine();

      if (GUILayout.Button($"Build for '{EditorUserBuildSettings.activeBuildTarget}'")) {
        builder_.Build(EditorUserBuildSettings.activeBuildTarget, authorMeta_, packs_);
      }
    }

    private void DrawHorizontalGUILine(int height = 1) {
      GUILayout.Space(OFFSET);

      var rect = GUILayoutUtility.GetRect(1.0f, height, GUILayout.ExpandWidth(true));
      rect.height = height;
      rect.xMin = 0;
      rect.xMax = EditorGUIUtility.currentViewWidth;

      var lineColor = new Color32(0x19, 0x19, 0x19, 0xff);
      EditorGUI.DrawRect(rect, lineColor);
      GUILayout.Space(OFFSET);
    }

    private bool EnsureMetaLoaded() {
      Refresh();

      return authorMeta_;
    }

    private void Refresh() {
      authorMeta_ = AuthorMeta.GetInstance();

      packs_.Clear();
      packs_.AddRange(PartPackMeta.GetAllInstances());
    }
  }
}