using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

// DO NOT EDIT THIS FILE
namespace Editor {
	internal class CarPartsBuilder {
		internal void Build(BuildTarget target, CarPartsBuilderMeta builder, AuthorMeta author, IReadOnlyCollection<CarPartsMeta> packs) {
			if (!Validate(author, packs, out string error)) {
				Debug.LogError($"Kino: Unable to build packs, validation error: {error}");
				return;
			}

			Debug.Log($"Kino: Build started for '{target}'");

			builder.Validate();

			foreach (var pack in packs) {
				if (!pack.SelectedToBuild) {
					continue;
				}

				BuildPackBundle(target, builder, author, pack);
			}
		}

		private void BuildPackBundle(BuildTarget target, CarPartsBuilderMeta builder, AuthorMeta author, CarPartsMeta pack) {
			Debug.Log($"Kino: Processing pack '{pack.PackName}'");

			string packFileName = $"{pack.PackName}{CarPartsBuilderMeta.PACK_EXT}";

			string packRootFolder = pack.GetRoot();

			var proxy = pack.GetProxyMeta();
			if (proxy == null) {
				Debug.LogError($"Kino: Unable to build pack '{pack.PackName}', failed to create metadata");
				return;
			}

			proxy.AuthorName = author.Name;

			if (!SaveProxyMetaToTxt(packRootFolder, proxy)) {
				Debug.LogError($"Kino: Unable to build pack '{pack.PackName}', failed to create metadata");
				return;
			}

			AssetDatabase.Refresh();

			var assets = new HashSet<string> {
				Path.Combine(packRootFolder, CarPartsMeta.PACK_META_RESERVED_NAME)
			};

			if (!string.IsNullOrWhiteSpace(proxy.PackIcon)) {
				assets.Add(proxy.PackIcon);
			}

			foreach (var part in proxy.Parts) {
				if (string.IsNullOrWhiteSpace(part.FilePath)) {
					Debug.LogWarning($"Kino: Skipped invalid part ({part.Id}) in '{proxy.Name}'");
					continue;
				}

				assets.Add(part.FilePath);

				if (!string.IsNullOrWhiteSpace(part.IconPath)) {
					assets.Add(part.IconPath);
				}
			}

			var builds = new[] {
				new AssetBundleBuild {
					assetBundleName = packFileName,
					assetNames = assets.ToArray()
				}
			};

			BuildPipeline.BuildAssetBundles(builder.BuildFolder, builds, BuildAssetBundleOptions.ForceRebuildAssetBundle, target);

			RunPostBuild(packFileName, builder, author, pack);
		}

		private void RunPostBuild(string fileName, CarPartsBuilderMeta builder, AuthorMeta author, CarPartsMeta meta) {
			string filePath = Path.Combine(builder.BuildFolder, fileName);

			if (!File.Exists(filePath)) {
				Debug.LogError($"Kino: Unable to locate pack bundle at '{filePath}'");
				return;
			}

			var fileContent = File.ReadAllBytes(filePath);

			using var fileStream = new FileStream(filePath, FileMode.Create);
			using var writer = new BinaryWriter(fileStream);

			writer.Write(CarPartsBuilderMeta.TOOL_VERSION);
			writer.Write(meta.Version);
			writer.Write((int) meta.Type);
			writer.Write(meta.Id);
			writer.Write(author.SteamId);
			writer.Write(author.DiscordId);
			writer.Write(fileContent.Length);
			writer.Write(fileContent);
		}

		private bool Validate(AuthorMeta author, IReadOnlyCollection<CarPartsMeta> packs, out string error) {
			error = string.Empty;

			if (!author.Validate()) {
				error = "See errors above";
				return false;
			}

			if (packs.Count == 0) {
				error = "Nothing to build";
				return false;
			}

			foreach (var pack in packs) {
				if (!pack.SelectedToBuild) {
					continue;
				}

				if (string.IsNullOrWhiteSpace(pack.PackName)
				    || string.IsNullOrWhiteSpace(pack.Description)
				    || string.IsNullOrWhiteSpace(pack.CategoryName)) {
					error = "One of selected to build packs has empty fields";
					return false;
				}

				var regex = new Regex("^[A-Za-z0-9_\\-]+$");
				if (!regex.IsMatch(pack.PackName)) {
					error = "Pack name contains not allowed characters. Allowed characters: [A-Z,a-z,0-9,-,_]";
					return false;
				}

				if (pack.Version <= 0) {
					error = $"Invalid pack version: {pack.PackName} -> {pack.Version}";
					return false;
				}

				if (!pack.ForceValidate()) {
					error = "See warnings above";
					return false;
				}
			}

			return true;
		}

		private bool SaveProxyMetaToTxt(string packRoot, CarPartsMeta.Proxy meta) {
			if (string.IsNullOrWhiteSpace(packRoot) || meta == null) {
				return false;
			}

			try {
				string json = JsonUtility.ToJson(meta, true);

				using var stream = new FileStream(Path.Combine(packRoot, CarPartsMeta.PACK_META_RESERVED_NAME), FileMode.Create, FileAccess.Write);
				using var writer = new StreamWriter(stream, Encoding.UTF8);
				writer.Write(json);

				return true;
			}
			catch (Exception e) {
				Debug.LogError($"Kino: Unable to save pack meta, exception: {e}");
				return false;
			}
		}
	}
}